module Sqlite3.Bindings.Internal.Constants
  ( SQLITE_OPEN_FLAGS (..),
    pattern SQLITE_OPEN_EXRESCODE,
    pattern SQLITE_OPEN_FULLMUTEX,
    pattern SQLITE_OPEN_MEMORY,
    pattern SQLITE_OPEN_NOFOLLOW,
    pattern SQLITE_OPEN_NOMUTEX,
    pattern SQLITE_OPEN_URI,
    SQLITE_OPEN_MODE (..),
    pattern SQLITE_OPEN_READONLY,
    pattern SQLITE_OPEN_READWRITE,
    pattern SQLITE_OPEN_CREATE,
    Sqlite.Bindings._SQLITE_ABORT,
    Sqlite.Bindings._SQLITE_ABORT_ROLLBACK,
    Sqlite.Bindings._SQLITE_ACCESS_EXISTS,
    Sqlite.Bindings._SQLITE_ACCESS_READ,
    Sqlite.Bindings._SQLITE_ACCESS_READWRITE,
    Sqlite.Bindings._SQLITE_ALTER_TABLE,
    Sqlite.Bindings._SQLITE_ANALYZE,
    Sqlite.Bindings._SQLITE_ANY,
    Sqlite.Bindings._SQLITE_ATTACH,
    Sqlite.Bindings._SQLITE_AUTH,
    Sqlite.Bindings._SQLITE_AUTH_USER,
    Sqlite.Bindings._SQLITE_BLOB,
    Sqlite.Bindings._SQLITE_BUSY,
    Sqlite.Bindings._SQLITE_BUSY_RECOVERY,
    Sqlite.Bindings._SQLITE_BUSY_SNAPSHOT,
    Sqlite.Bindings._SQLITE_BUSY_TIMEOUT,
    Sqlite.Bindings._SQLITE_CANTOPEN,
    Sqlite.Bindings._SQLITE_CANTOPEN_CONVPATH,
    Sqlite.Bindings._SQLITE_CANTOPEN_DIRTYWAL,
    Sqlite.Bindings._SQLITE_CANTOPEN_FULLPATH,
    Sqlite.Bindings._SQLITE_CANTOPEN_ISDIR,
    Sqlite.Bindings._SQLITE_CANTOPEN_NOTEMPDIR,
    Sqlite.Bindings._SQLITE_CANTOPEN_SYMLINK,
    Sqlite.Bindings._SQLITE_CHECKPOINT_FULL,
    Sqlite.Bindings._SQLITE_CHECKPOINT_PASSIVE,
    Sqlite.Bindings._SQLITE_CHECKPOINT_RESTART,
    Sqlite.Bindings._SQLITE_CHECKPOINT_TRUNCATE,
    Sqlite.Bindings._SQLITE_CONFIG_COVERING_INDEX_SCAN,
    Sqlite.Bindings._SQLITE_CONFIG_GETMALLOC,
    Sqlite.Bindings._SQLITE_CONFIG_GETMUTEX,
    Sqlite.Bindings._SQLITE_CONFIG_GETPCACHE2,
    Sqlite.Bindings._SQLITE_CONFIG_HEAP,
    Sqlite.Bindings._SQLITE_CONFIG_LOG,
    Sqlite.Bindings._SQLITE_CONFIG_LOOKASIDE,
    Sqlite.Bindings._SQLITE_CONFIG_MALLOC,
    Sqlite.Bindings._SQLITE_CONFIG_MEMDB_MAXSIZE,
    Sqlite.Bindings._SQLITE_CONFIG_MEMSTATUS,
    Sqlite.Bindings._SQLITE_CONFIG_MMAP_SIZE,
    Sqlite.Bindings._SQLITE_CONFIG_MULTITHREAD,
    Sqlite.Bindings._SQLITE_CONFIG_MUTEX,
    Sqlite.Bindings._SQLITE_CONFIG_PAGECACHE,
    Sqlite.Bindings._SQLITE_CONFIG_PCACHE2,
    Sqlite.Bindings._SQLITE_CONFIG_PCACHE_HDRSZ,
    Sqlite.Bindings._SQLITE_CONFIG_PMASZ,
    Sqlite.Bindings._SQLITE_CONFIG_SERIALIZED,
    Sqlite.Bindings._SQLITE_CONFIG_SINGLETHREAD,
    Sqlite.Bindings._SQLITE_CONFIG_SMALL_MALLOC,
    Sqlite.Bindings._SQLITE_CONFIG_SORTERREF_SIZE,
    Sqlite.Bindings._SQLITE_CONFIG_SQLLOG,
    Sqlite.Bindings._SQLITE_CONFIG_STMTJRNL_SPILL,
    Sqlite.Bindings._SQLITE_CONFIG_URI,
    Sqlite.Bindings._SQLITE_CONFIG_WIN32_HEAPSIZE,
    Sqlite.Bindings._SQLITE_CONSTRAINT,
    Sqlite.Bindings._SQLITE_CONSTRAINT_CHECK,
    Sqlite.Bindings._SQLITE_CONSTRAINT_COMMITHOOK,
    Sqlite.Bindings._SQLITE_CONSTRAINT_DATATYPE,
    Sqlite.Bindings._SQLITE_CONSTRAINT_FOREIGNKEY,
    Sqlite.Bindings._SQLITE_CONSTRAINT_FUNCTION,
    Sqlite.Bindings._SQLITE_CONSTRAINT_NOTNULL,
    Sqlite.Bindings._SQLITE_CONSTRAINT_PINNED,
    Sqlite.Bindings._SQLITE_CONSTRAINT_PRIMARYKEY,
    Sqlite.Bindings._SQLITE_CONSTRAINT_ROWID,
    Sqlite.Bindings._SQLITE_CONSTRAINT_TRIGGER,
    Sqlite.Bindings._SQLITE_CONSTRAINT_UNIQUE,
    Sqlite.Bindings._SQLITE_CONSTRAINT_VTAB,
    Sqlite.Bindings._SQLITE_COPY,
    Sqlite.Bindings._SQLITE_CORRUPT,
    Sqlite.Bindings._SQLITE_CORRUPT_INDEX,
    Sqlite.Bindings._SQLITE_CORRUPT_SEQUENCE,
    Sqlite.Bindings._SQLITE_CORRUPT_VTAB,
    Sqlite.Bindings._SQLITE_CREATE_INDEX,
    Sqlite.Bindings._SQLITE_CREATE_TABLE,
    Sqlite.Bindings._SQLITE_CREATE_TEMP_INDEX,
    Sqlite.Bindings._SQLITE_CREATE_TEMP_TABLE,
    Sqlite.Bindings._SQLITE_CREATE_TEMP_TRIGGER,
    Sqlite.Bindings._SQLITE_CREATE_TEMP_VIEW,
    Sqlite.Bindings._SQLITE_CREATE_TRIGGER,
    Sqlite.Bindings._SQLITE_CREATE_VIEW,
    Sqlite.Bindings._SQLITE_CREATE_VTABLE,
    Sqlite.Bindings._SQLITE_DBCONFIG_DEFENSIVE,
    Sqlite.Bindings._SQLITE_DBCONFIG_DQS_DDL,
    Sqlite.Bindings._SQLITE_DBCONFIG_DQS_DML,
    Sqlite.Bindings._SQLITE_DBCONFIG_ENABLE_FKEY,
    Sqlite.Bindings._SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER,
    Sqlite.Bindings._SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION,
    Sqlite.Bindings._SQLITE_DBCONFIG_ENABLE_QPSG,
    Sqlite.Bindings._SQLITE_DBCONFIG_ENABLE_TRIGGER,
    Sqlite.Bindings._SQLITE_DBCONFIG_ENABLE_VIEW,
    Sqlite.Bindings._SQLITE_DBCONFIG_LEGACY_ALTER_TABLE,
    Sqlite.Bindings._SQLITE_DBCONFIG_LEGACY_FILE_FORMAT,
    Sqlite.Bindings._SQLITE_DBCONFIG_LOOKASIDE,
    Sqlite.Bindings._SQLITE_DBCONFIG_MAINDBNAME,
    Sqlite.Bindings._SQLITE_DBCONFIG_MAX,
    Sqlite.Bindings._SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE,
    Sqlite.Bindings._SQLITE_DBCONFIG_RESET_DATABASE,
    Sqlite.Bindings._SQLITE_DBCONFIG_TRIGGER_EQP,
    Sqlite.Bindings._SQLITE_DBCONFIG_TRUSTED_SCHEMA,
    Sqlite.Bindings._SQLITE_DBCONFIG_WRITABLE_SCHEMA,
    Sqlite.Bindings._SQLITE_DBSTATUS_CACHE_HIT,
    Sqlite.Bindings._SQLITE_DBSTATUS_CACHE_MISS,
    Sqlite.Bindings._SQLITE_DBSTATUS_CACHE_SPILL,
    Sqlite.Bindings._SQLITE_DBSTATUS_CACHE_USED,
    Sqlite.Bindings._SQLITE_DBSTATUS_CACHE_USED_SHARED,
    Sqlite.Bindings._SQLITE_DBSTATUS_CACHE_WRITE,
    Sqlite.Bindings._SQLITE_DBSTATUS_DEFERRED_FKS,
    Sqlite.Bindings._SQLITE_DBSTATUS_LOOKASIDE_HIT,
    Sqlite.Bindings._SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL,
    Sqlite.Bindings._SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE,
    Sqlite.Bindings._SQLITE_DBSTATUS_LOOKASIDE_USED,
    Sqlite.Bindings._SQLITE_DBSTATUS_MAX,
    Sqlite.Bindings._SQLITE_DBSTATUS_SCHEMA_USED,
    Sqlite.Bindings._SQLITE_DBSTATUS_STMT_USED,
    Sqlite.Bindings._SQLITE_DELETE,
    Sqlite.Bindings._SQLITE_DENY,
    Sqlite.Bindings._SQLITE_DESERIALIZE_FREEONCLOSE,
    Sqlite.Bindings._SQLITE_DESERIALIZE_READONLY,
    Sqlite.Bindings._SQLITE_DESERIALIZE_RESIZEABLE,
    Sqlite.Bindings._SQLITE_DETACH,
    Sqlite.Bindings._SQLITE_DETERMINISTIC,
    Sqlite.Bindings._SQLITE_DIRECTONLY,
    Sqlite.Bindings._SQLITE_DONE,
    Sqlite.Bindings._SQLITE_DROP_INDEX,
    Sqlite.Bindings._SQLITE_DROP_TABLE,
    Sqlite.Bindings._SQLITE_DROP_TEMP_INDEX,
    Sqlite.Bindings._SQLITE_DROP_TEMP_TABLE,
    Sqlite.Bindings._SQLITE_DROP_TEMP_TRIGGER,
    Sqlite.Bindings._SQLITE_DROP_TEMP_VIEW,
    Sqlite.Bindings._SQLITE_DROP_TRIGGER,
    Sqlite.Bindings._SQLITE_DROP_VIEW,
    Sqlite.Bindings._SQLITE_DROP_VTABLE,
    Sqlite.Bindings._SQLITE_EMPTY,
    Sqlite.Bindings._SQLITE_ERROR,
    Sqlite.Bindings._SQLITE_ERROR_MISSING_COLLSEQ,
    Sqlite.Bindings._SQLITE_ERROR_RETRY,
    Sqlite.Bindings._SQLITE_ERROR_SNAPSHOT,
    Sqlite.Bindings._SQLITE_FAIL,
    Sqlite.Bindings._SQLITE_FCNTL_BEGIN_ATOMIC_WRITE,
    Sqlite.Bindings._SQLITE_FCNTL_BUSYHANDLER,
    Sqlite.Bindings._SQLITE_FCNTL_CHUNK_SIZE,
    Sqlite.Bindings._SQLITE_FCNTL_CKPT_DONE,
    Sqlite.Bindings._SQLITE_FCNTL_CKPT_START,
    Sqlite.Bindings._SQLITE_FCNTL_CKSM_FILE,
    Sqlite.Bindings._SQLITE_FCNTL_COMMIT_ATOMIC_WRITE,
    Sqlite.Bindings._SQLITE_FCNTL_COMMIT_PHASETWO,
    Sqlite.Bindings._SQLITE_FCNTL_DATA_VERSION,
    Sqlite.Bindings._SQLITE_FCNTL_EXTERNAL_READER,
    Sqlite.Bindings._SQLITE_FCNTL_FILE_POINTER,
    Sqlite.Bindings._SQLITE_FCNTL_GET_LOCKPROXYFILE,
    Sqlite.Bindings._SQLITE_FCNTL_HAS_MOVED,
    Sqlite.Bindings._SQLITE_FCNTL_JOURNAL_POINTER,
    Sqlite.Bindings._SQLITE_FCNTL_LAST_ERRNO,
    Sqlite.Bindings._SQLITE_FCNTL_LOCKSTATE,
    Sqlite.Bindings._SQLITE_FCNTL_LOCK_TIMEOUT,
    Sqlite.Bindings._SQLITE_FCNTL_MMAP_SIZE,
    Sqlite.Bindings._SQLITE_FCNTL_OVERWRITE,
    Sqlite.Bindings._SQLITE_FCNTL_PDB,
    Sqlite.Bindings._SQLITE_FCNTL_PERSIST_WAL,
    Sqlite.Bindings._SQLITE_FCNTL_POWERSAFE_OVERWRITE,
    Sqlite.Bindings._SQLITE_FCNTL_PRAGMA,
    Sqlite.Bindings._SQLITE_FCNTL_RBU,
    Sqlite.Bindings._SQLITE_FCNTL_RESERVE_BYTES,
    Sqlite.Bindings._SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE,
    Sqlite.Bindings._SQLITE_FCNTL_SET_LOCKPROXYFILE,
    Sqlite.Bindings._SQLITE_FCNTL_SIZE_HINT,
    Sqlite.Bindings._SQLITE_FCNTL_SIZE_LIMIT,
    Sqlite.Bindings._SQLITE_FCNTL_SYNC,
    Sqlite.Bindings._SQLITE_FCNTL_SYNC_OMITTED,
    Sqlite.Bindings._SQLITE_FCNTL_TEMPFILENAME,
    Sqlite.Bindings._SQLITE_FCNTL_TRACE,
    Sqlite.Bindings._SQLITE_FCNTL_VFSNAME,
    Sqlite.Bindings._SQLITE_FCNTL_VFS_POINTER,
    Sqlite.Bindings._SQLITE_FCNTL_WAL_BLOCK,
    Sqlite.Bindings._SQLITE_FCNTL_WIN32_AV_RETRY,
    Sqlite.Bindings._SQLITE_FCNTL_WIN32_GET_HANDLE,
    Sqlite.Bindings._SQLITE_FCNTL_WIN32_SET_HANDLE,
    Sqlite.Bindings._SQLITE_FCNTL_ZIPVFS,
    Sqlite.Bindings._SQLITE_FLOAT,
    Sqlite.Bindings._SQLITE_FORMAT,
    Sqlite.Bindings._SQLITE_FULL,
    Sqlite.Bindings._SQLITE_FUNCTION,
    Sqlite.Bindings._SQLITE_IGNORE,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_EQ,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_FUNCTION,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_GE,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_GLOB,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_GT,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_IS,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_ISNOT,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_ISNOTNULL,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_ISNULL,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_LE,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_LIKE,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_LIMIT,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_LT,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_MATCH,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_NE,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_OFFSET,
    Sqlite.Bindings._SQLITE_INDEX_CONSTRAINT_REGEXP,
    Sqlite.Bindings._SQLITE_INDEX_SCAN_UNIQUE,
    Sqlite.Bindings._SQLITE_INNOCUOUS,
    Sqlite.Bindings._SQLITE_INSERT,
    Sqlite.Bindings._SQLITE_INTEGER,
    Sqlite.Bindings._SQLITE_INTERNAL,
    Sqlite.Bindings._SQLITE_INTERRUPT,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC16K,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC1K,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC2K,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC32K,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC4K,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC512,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC64K,
    Sqlite.Bindings._SQLITE_IOCAP_ATOMIC8K,
    Sqlite.Bindings._SQLITE_IOCAP_BATCH_ATOMIC,
    Sqlite.Bindings._SQLITE_IOCAP_IMMUTABLE,
    Sqlite.Bindings._SQLITE_IOCAP_POWERSAFE_OVERWRITE,
    Sqlite.Bindings._SQLITE_IOCAP_SAFE_APPEND,
    Sqlite.Bindings._SQLITE_IOCAP_SEQUENTIAL,
    Sqlite.Bindings._SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN,
    Sqlite.Bindings._SQLITE_IOERR,
    Sqlite.Bindings._SQLITE_IOERR_ACCESS,
    Sqlite.Bindings._SQLITE_IOERR_AUTH,
    Sqlite.Bindings._SQLITE_IOERR_BEGIN_ATOMIC,
    Sqlite.Bindings._SQLITE_IOERR_BLOCKED,
    Sqlite.Bindings._SQLITE_IOERR_CHECKRESERVEDLOCK,
    Sqlite.Bindings._SQLITE_IOERR_CLOSE,
    Sqlite.Bindings._SQLITE_IOERR_COMMIT_ATOMIC,
    Sqlite.Bindings._SQLITE_IOERR_CONVPATH,
    Sqlite.Bindings._SQLITE_IOERR_CORRUPTFS,
    Sqlite.Bindings._SQLITE_IOERR_DATA,
    Sqlite.Bindings._SQLITE_IOERR_DELETE,
    Sqlite.Bindings._SQLITE_IOERR_DELETE_NOENT,
    Sqlite.Bindings._SQLITE_IOERR_DIR_CLOSE,
    Sqlite.Bindings._SQLITE_IOERR_DIR_FSYNC,
    Sqlite.Bindings._SQLITE_IOERR_FSTAT,
    Sqlite.Bindings._SQLITE_IOERR_FSYNC,
    Sqlite.Bindings._SQLITE_IOERR_GETTEMPPATH,
    Sqlite.Bindings._SQLITE_IOERR_LOCK,
    Sqlite.Bindings._SQLITE_IOERR_MMAP,
    Sqlite.Bindings._SQLITE_IOERR_NOMEM,
    Sqlite.Bindings._SQLITE_IOERR_RDLOCK,
    Sqlite.Bindings._SQLITE_IOERR_READ,
    Sqlite.Bindings._SQLITE_IOERR_ROLLBACK_ATOMIC,
    Sqlite.Bindings._SQLITE_IOERR_SEEK,
    Sqlite.Bindings._SQLITE_IOERR_SHMLOCK,
    Sqlite.Bindings._SQLITE_IOERR_SHMMAP,
    Sqlite.Bindings._SQLITE_IOERR_SHMOPEN,
    Sqlite.Bindings._SQLITE_IOERR_SHMSIZE,
    Sqlite.Bindings._SQLITE_IOERR_SHORT_READ,
    Sqlite.Bindings._SQLITE_IOERR_TRUNCATE,
    Sqlite.Bindings._SQLITE_IOERR_UNLOCK,
    Sqlite.Bindings._SQLITE_IOERR_VNODE,
    Sqlite.Bindings._SQLITE_IOERR_WRITE,
    Sqlite.Bindings._SQLITE_LIMIT_ATTACHED,
    Sqlite.Bindings._SQLITE_LIMIT_COLUMN,
    Sqlite.Bindings._SQLITE_LIMIT_COMPOUND_SELECT,
    Sqlite.Bindings._SQLITE_LIMIT_EXPR_DEPTH,
    Sqlite.Bindings._SQLITE_LIMIT_FUNCTION_ARG,
    Sqlite.Bindings._SQLITE_LIMIT_LENGTH,
    Sqlite.Bindings._SQLITE_LIMIT_LIKE_PATTERN_LENGTH,
    Sqlite.Bindings._SQLITE_LIMIT_SQL_LENGTH,
    Sqlite.Bindings._SQLITE_LIMIT_TRIGGER_DEPTH,
    Sqlite.Bindings._SQLITE_LIMIT_VARIABLE_NUMBER,
    Sqlite.Bindings._SQLITE_LIMIT_VDBE_OP,
    Sqlite.Bindings._SQLITE_LIMIT_WORKER_THREADS,
    Sqlite.Bindings._SQLITE_LOCKED,
    Sqlite.Bindings._SQLITE_LOCKED_SHAREDCACHE,
    Sqlite.Bindings._SQLITE_LOCKED_VTAB,
    Sqlite.Bindings._SQLITE_LOCK_EXCLUSIVE,
    Sqlite.Bindings._SQLITE_LOCK_NONE,
    Sqlite.Bindings._SQLITE_LOCK_PENDING,
    Sqlite.Bindings._SQLITE_LOCK_RESERVED,
    Sqlite.Bindings._SQLITE_LOCK_SHARED,
    Sqlite.Bindings._SQLITE_MISMATCH,
    Sqlite.Bindings._SQLITE_MISUSE,
    Sqlite.Bindings._SQLITE_MUTEX_FAST,
    Sqlite.Bindings._SQLITE_MUTEX_RECURSIVE,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_APP1,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_APP2,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_APP3,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_LRU,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_LRU2,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_MAIN,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_MEM,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_MEM2,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_OPEN,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_PMEM,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_PRNG,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_VFS1,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_VFS2,
    Sqlite.Bindings._SQLITE_MUTEX_STATIC_VFS3,
    Sqlite.Bindings._SQLITE_NOLFS,
    Sqlite.Bindings._SQLITE_NOMEM,
    Sqlite.Bindings._SQLITE_NOTADB,
    Sqlite.Bindings._SQLITE_NOTFOUND,
    Sqlite.Bindings._SQLITE_NOTICE,
    Sqlite.Bindings._SQLITE_NOTICE_RECOVER_ROLLBACK,
    Sqlite.Bindings._SQLITE_NOTICE_RECOVER_WAL,
    Sqlite.Bindings._SQLITE_NULL,
    Sqlite.Bindings._SQLITE_OK,
    Sqlite.Bindings._SQLITE_OK_LOAD_PERMANENTLY,
    Sqlite.Bindings._SQLITE_OK_SYMLINK,
    Sqlite.Bindings._SQLITE_OPEN_AUTOPROXY,
    Sqlite.Bindings._SQLITE_OPEN_DELETEONCLOSE,
    Sqlite.Bindings._SQLITE_OPEN_EXCLUSIVE,
    Sqlite.Bindings._SQLITE_OPEN_MAIN_DB,
    Sqlite.Bindings._SQLITE_OPEN_MAIN_JOURNAL,
    Sqlite.Bindings._SQLITE_OPEN_SUBJOURNAL,
    Sqlite.Bindings._SQLITE_OPEN_SUPER_JOURNAL,
    Sqlite.Bindings._SQLITE_OPEN_TEMP_DB,
    Sqlite.Bindings._SQLITE_OPEN_TEMP_JOURNAL,
    Sqlite.Bindings._SQLITE_OPEN_TRANSIENT_DB,
    Sqlite.Bindings._SQLITE_OPEN_WAL,
    Sqlite.Bindings._SQLITE_PERM,
    Sqlite.Bindings._SQLITE_PRAGMA,
    Sqlite.Bindings._SQLITE_PREPARE_NORMALIZE,
    Sqlite.Bindings._SQLITE_PREPARE_NO_VTAB,
    Sqlite.Bindings._SQLITE_PREPARE_PERSISTENT,
    Sqlite.Bindings._SQLITE_PROTOCOL,
    Sqlite.Bindings._SQLITE_RANGE,
    Sqlite.Bindings._SQLITE_READ,
    Sqlite.Bindings._SQLITE_READONLY,
    Sqlite.Bindings._SQLITE_READONLY_CANTINIT,
    Sqlite.Bindings._SQLITE_READONLY_CANTLOCK,
    Sqlite.Bindings._SQLITE_READONLY_DBMOVED,
    Sqlite.Bindings._SQLITE_READONLY_DIRECTORY,
    Sqlite.Bindings._SQLITE_READONLY_RECOVERY,
    Sqlite.Bindings._SQLITE_READONLY_ROLLBACK,
    Sqlite.Bindings._SQLITE_RECURSIVE,
    Sqlite.Bindings._SQLITE_REINDEX,
    Sqlite.Bindings._SQLITE_REPLACE,
    Sqlite.Bindings._SQLITE_ROLLBACK,
    Sqlite.Bindings._SQLITE_ROW,
    Sqlite.Bindings._SQLITE_SAVEPOINT,
    Sqlite.Bindings._SQLITE_SCANSTAT_EST,
    Sqlite.Bindings._SQLITE_SCANSTAT_EXPLAIN,
    Sqlite.Bindings._SQLITE_SCANSTAT_NAME,
    Sqlite.Bindings._SQLITE_SCANSTAT_NLOOP,
    Sqlite.Bindings._SQLITE_SCANSTAT_NVISIT,
    Sqlite.Bindings._SQLITE_SCANSTAT_SELECTID,
    Sqlite.Bindings._SQLITE_SCHEMA,
    Sqlite.Bindings._SQLITE_SELECT,
    Sqlite.Bindings._SQLITE_SERIALIZE_NOCOPY,
    Sqlite.Bindings._SQLITE_SHM_EXCLUSIVE,
    Sqlite.Bindings._SQLITE_SHM_LOCK,
    Sqlite.Bindings._SQLITE_SHM_NLOCK,
    Sqlite.Bindings._SQLITE_SHM_SHARED,
    Sqlite.Bindings._SQLITE_SHM_UNLOCK,
    Sqlite.Bindings._SQLITE_SOURCE_ID,
    Sqlite.Bindings._SQLITE_STATIC,
    Sqlite.Bindings._SQLITE_STATUS_MALLOC_COUNT,
    Sqlite.Bindings._SQLITE_STATUS_MALLOC_SIZE,
    Sqlite.Bindings._SQLITE_STATUS_MEMORY_USED,
    Sqlite.Bindings._SQLITE_STATUS_PAGECACHE_OVERFLOW,
    Sqlite.Bindings._SQLITE_STATUS_PAGECACHE_SIZE,
    Sqlite.Bindings._SQLITE_STATUS_PAGECACHE_USED,
    Sqlite.Bindings._SQLITE_STATUS_PARSER_STACK,
    Sqlite.Bindings._SQLITE_STATUS_SCRATCH_OVERFLOW,
    Sqlite.Bindings._SQLITE_STATUS_SCRATCH_SIZE,
    Sqlite.Bindings._SQLITE_STATUS_SCRATCH_USED,
    Sqlite.Bindings._SQLITE_STMTSTATUS_AUTOINDEX,
    Sqlite.Bindings._SQLITE_STMTSTATUS_FILTER_HIT,
    Sqlite.Bindings._SQLITE_STMTSTATUS_FILTER_MISS,
    Sqlite.Bindings._SQLITE_STMTSTATUS_FULLSCAN_STEP,
    Sqlite.Bindings._SQLITE_STMTSTATUS_MEMUSED,
    Sqlite.Bindings._SQLITE_STMTSTATUS_REPREPARE,
    Sqlite.Bindings._SQLITE_STMTSTATUS_RUN,
    Sqlite.Bindings._SQLITE_STMTSTATUS_SORT,
    Sqlite.Bindings._SQLITE_STMTSTATUS_VM_STEP,
    Sqlite.Bindings._SQLITE_SUBTYPE,
    Sqlite.Bindings._SQLITE_SYNC_DATAONLY,
    Sqlite.Bindings._SQLITE_SYNC_FULL,
    Sqlite.Bindings._SQLITE_SYNC_NORMAL,
    Sqlite.Bindings._SQLITE_TESTCTRL_ALWAYS,
    Sqlite.Bindings._SQLITE_TESTCTRL_ASSERT,
    Sqlite.Bindings._SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS,
    Sqlite.Bindings._SQLITE_TESTCTRL_BITVEC_TEST,
    Sqlite.Bindings._SQLITE_TESTCTRL_BYTEORDER,
    Sqlite.Bindings._SQLITE_TESTCTRL_EXPLAIN_STMT,
    Sqlite.Bindings._SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS,
    Sqlite.Bindings._SQLITE_TESTCTRL_FAULT_INSTALL,
    Sqlite.Bindings._SQLITE_TESTCTRL_FIRST,
    Sqlite.Bindings._SQLITE_TESTCTRL_IMPOSTER,
    Sqlite.Bindings._SQLITE_TESTCTRL_INTERNAL_FUNCTIONS,
    Sqlite.Bindings._SQLITE_TESTCTRL_ISINIT,
    Sqlite.Bindings._SQLITE_TESTCTRL_ISKEYWORD,
    Sqlite.Bindings._SQLITE_TESTCTRL_LAST,
    Sqlite.Bindings._SQLITE_TESTCTRL_LOCALTIME_FAULT,
    Sqlite.Bindings._SQLITE_TESTCTRL_LOGEST,
    Sqlite.Bindings._SQLITE_TESTCTRL_NEVER_CORRUPT,
    Sqlite.Bindings._SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD,
    Sqlite.Bindings._SQLITE_TESTCTRL_OPTIMIZATIONS,
    Sqlite.Bindings._SQLITE_TESTCTRL_PARSER_COVERAGE,
    Sqlite.Bindings._SQLITE_TESTCTRL_PENDING_BYTE,
    Sqlite.Bindings._SQLITE_TESTCTRL_PRNG_RESET,
    Sqlite.Bindings._SQLITE_TESTCTRL_PRNG_RESTORE,
    Sqlite.Bindings._SQLITE_TESTCTRL_PRNG_SAVE,
    Sqlite.Bindings._SQLITE_TESTCTRL_PRNG_SEED,
    Sqlite.Bindings._SQLITE_TESTCTRL_RESERVE,
    Sqlite.Bindings._SQLITE_TESTCTRL_RESULT_INTREAL,
    Sqlite.Bindings._SQLITE_TESTCTRL_SCRATCHMALLOC,
    Sqlite.Bindings._SQLITE_TESTCTRL_SEEK_COUNT,
    Sqlite.Bindings._SQLITE_TESTCTRL_SORTER_MMAP,
    Sqlite.Bindings._SQLITE_TESTCTRL_TRACEFLAGS,
    Sqlite.Bindings._SQLITE_TESTCTRL_TUNE,
    Sqlite.Bindings._SQLITE_TESTCTRL_VDBE_COVERAGE,
    Sqlite.Bindings._SQLITE_TEXT,
    Sqlite.Bindings._SQLITE_TOOBIG,
    Sqlite.Bindings._SQLITE_TRACE_CLOSE,
    Sqlite.Bindings._SQLITE_TRACE_PROFILE,
    Sqlite.Bindings._SQLITE_TRACE_ROW,
    Sqlite.Bindings._SQLITE_TRACE_STMT,
    Sqlite.Bindings._SQLITE_TRANSACTION,
    Sqlite.Bindings._SQLITE_TRANSIENT,
    Sqlite.Bindings._SQLITE_TXN_NONE,
    Sqlite.Bindings._SQLITE_TXN_READ,
    Sqlite.Bindings._SQLITE_TXN_WRITE,
    Sqlite.Bindings._SQLITE_UPDATE,
    Sqlite.Bindings._SQLITE_UTF16,
    Sqlite.Bindings._SQLITE_UTF16BE,
    Sqlite.Bindings._SQLITE_UTF16LE,
    Sqlite.Bindings._SQLITE_UTF16_ALIGNED,
    Sqlite.Bindings._SQLITE_UTF8,
    Sqlite.Bindings._SQLITE_VERSION,
    Sqlite.Bindings._SQLITE_VERSION_NUMBER,
    Sqlite.Bindings._SQLITE_VTAB_CONSTRAINT_SUPPORT,
    Sqlite.Bindings._SQLITE_VTAB_DIRECTONLY,
    Sqlite.Bindings._SQLITE_VTAB_INNOCUOUS,
    Sqlite.Bindings._SQLITE_WARNING,
    Sqlite.Bindings._SQLITE_WARNING_AUTOINDEX,
    Sqlite.Bindings._SQLITE_WIN32_DATA_DIRECTORY_TYPE,
    Sqlite.Bindings._SQLITE_WIN32_TEMP_DIRECTORY_TYPE,
  )
where

import Data.Bits ((.|.))
import Data.Coerce (coerce)
import Foreign.C (CInt (..))
import qualified Sqlite.Bindings

-- | https://www.sqlite.org/c3ref/c_open_autoproxy.html
newtype SQLITE_OPEN_FLAGS
  = SQLITE_OPEN_FLAGS CInt
  deriving stock (Eq)

instance Monoid SQLITE_OPEN_FLAGS where
  mappend = (<>)
  mempty = SQLITE_OPEN_FLAGS 0

instance Semigroup SQLITE_OPEN_FLAGS where
  (<>) =
    coerce ((.|.) :: CInt -> CInt -> CInt)

pattern SQLITE_OPEN_EXRESCODE :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_EXRESCODE <-
  ((== SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_EXRESCODE) -> True)
  where
    SQLITE_OPEN_EXRESCODE = SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_EXRESCODE

pattern SQLITE_OPEN_FULLMUTEX :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_FULLMUTEX <-
  ((== SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_FULLMUTEX) -> True)
  where
    SQLITE_OPEN_FULLMUTEX = SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_FULLMUTEX

pattern SQLITE_OPEN_MEMORY :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_MEMORY <-
  ((== SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_MEMORY) -> True)
  where
    SQLITE_OPEN_MEMORY = SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_MEMORY

pattern SQLITE_OPEN_NOFOLLOW :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_NOFOLLOW <-
  ((== SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_NOFOLLOW) -> True)
  where
    SQLITE_OPEN_NOFOLLOW = SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_NOFOLLOW

pattern SQLITE_OPEN_NOMUTEX :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_NOMUTEX <-
  ((== SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_NOMUTEX) -> True)
  where
    SQLITE_OPEN_NOMUTEX = SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_NOMUTEX

pattern SQLITE_OPEN_URI :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_URI <-
  ((== SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_URI) -> True)
  where
    SQLITE_OPEN_URI = SQLITE_OPEN_FLAGS Sqlite.Bindings._SQLITE_OPEN_URI

{-# COMPLETE
  SQLITE_OPEN_EXRESCODE,
  SQLITE_OPEN_FULLMUTEX,
  SQLITE_OPEN_MEMORY,
  SQLITE_OPEN_NOFOLLOW,
  SQLITE_OPEN_NOMUTEX,
  SQLITE_OPEN_URI
  #-}

-- | https://www.sqlite.org/c3ref/c_open_autoproxy.html
newtype SQLITE_OPEN_MODE
  = SQLITE_OPEN_MODE CInt
  deriving stock (Eq)

pattern SQLITE_OPEN_READONLY :: SQLITE_OPEN_MODE
pattern SQLITE_OPEN_READONLY <-
  ((== SQLITE_OPEN_MODE Sqlite.Bindings._SQLITE_OPEN_READONLY) -> True)
  where
    SQLITE_OPEN_READONLY = SQLITE_OPEN_MODE Sqlite.Bindings._SQLITE_OPEN_READONLY

pattern SQLITE_OPEN_READWRITE :: SQLITE_OPEN_MODE
pattern SQLITE_OPEN_READWRITE <-
  ((== SQLITE_OPEN_MODE Sqlite.Bindings._SQLITE_OPEN_READWRITE) -> True)
  where
    SQLITE_OPEN_READWRITE = SQLITE_OPEN_MODE Sqlite.Bindings._SQLITE_OPEN_READWRITE

pattern SQLITE_OPEN_CREATE :: SQLITE_OPEN_MODE
pattern SQLITE_OPEN_CREATE <-
  ((== SQLITE_OPEN_MODE (Sqlite.Bindings._SQLITE_OPEN_READWRITE .|. Sqlite.Bindings._SQLITE_OPEN_CREATE)) -> True)
  where
    SQLITE_OPEN_CREATE =
      SQLITE_OPEN_MODE (Sqlite.Bindings._SQLITE_OPEN_READWRITE .|. Sqlite.Bindings._SQLITE_OPEN_CREATE)

{-# COMPLETE SQLITE_OPEN_READONLY, SQLITE_OPEN_READWRITE, SQLITE_OPEN_CREATE #-}
