module Sqlite3.Bindings.Internal.Constants
  ( SQLITE_DATATYPE (..),
    pattern SQLITE_INTEGER,
    pattern SQLITE_FLOAT,
    pattern SQLITE_TEXT,
    pattern SQLITE_BLOB,
    pattern SQLITE_NULL,
    SQLITE_OPEN_FLAGS (..),
    pattern SQLITE_OPEN_EXRESCODE,
    pattern SQLITE_OPEN_FULLMUTEX,
    pattern SQLITE_OPEN_MEMORY,
    pattern SQLITE_OPEN_NOFOLLOW,
    pattern SQLITE_OPEN_NOMUTEX,
    pattern SQLITE_OPEN_URI,
    SQLITE_OPEN_MODE (..),
    pattern SQLITE_OPEN_READONLY,
    pattern SQLITE_OPEN_READWRITE,
    pattern SQLITE_OPEN_CREATE,
    C._SQLITE_ABORT,
    C._SQLITE_ABORT_ROLLBACK,
    C._SQLITE_ACCESS_EXISTS,
    C._SQLITE_ACCESS_READ,
    C._SQLITE_ACCESS_READWRITE,
    C._SQLITE_ALTER_TABLE,
    C._SQLITE_ANALYZE,
    C._SQLITE_ANY,
    C._SQLITE_ATTACH,
    C._SQLITE_AUTH,
    C._SQLITE_AUTH_USER,
    C._SQLITE_BLOB,
    C._SQLITE_BUSY,
    C._SQLITE_BUSY_RECOVERY,
    C._SQLITE_BUSY_SNAPSHOT,
    C._SQLITE_BUSY_TIMEOUT,
    C._SQLITE_CANTOPEN,
    C._SQLITE_CANTOPEN_CONVPATH,
    C._SQLITE_CANTOPEN_DIRTYWAL,
    C._SQLITE_CANTOPEN_FULLPATH,
    C._SQLITE_CANTOPEN_ISDIR,
    C._SQLITE_CANTOPEN_NOTEMPDIR,
    C._SQLITE_CANTOPEN_SYMLINK,
    C._SQLITE_CHECKPOINT_FULL,
    C._SQLITE_CHECKPOINT_PASSIVE,
    C._SQLITE_CHECKPOINT_RESTART,
    C._SQLITE_CHECKPOINT_TRUNCATE,
    C._SQLITE_CONSTRAINT,
    C._SQLITE_CONSTRAINT_CHECK,
    C._SQLITE_CONSTRAINT_COMMITHOOK,
    C._SQLITE_CONSTRAINT_DATATYPE,
    C._SQLITE_CONSTRAINT_FOREIGNKEY,
    C._SQLITE_CONSTRAINT_FUNCTION,
    C._SQLITE_CONSTRAINT_NOTNULL,
    C._SQLITE_CONSTRAINT_PINNED,
    C._SQLITE_CONSTRAINT_PRIMARYKEY,
    C._SQLITE_CONSTRAINT_ROWID,
    C._SQLITE_CONSTRAINT_TRIGGER,
    C._SQLITE_CONSTRAINT_UNIQUE,
    C._SQLITE_CONSTRAINT_VTAB,
    C._SQLITE_COPY,
    C._SQLITE_CORRUPT,
    C._SQLITE_CORRUPT_INDEX,
    C._SQLITE_CORRUPT_SEQUENCE,
    C._SQLITE_CORRUPT_VTAB,
    C._SQLITE_CREATE_INDEX,
    C._SQLITE_CREATE_TABLE,
    C._SQLITE_CREATE_TEMP_INDEX,
    C._SQLITE_CREATE_TEMP_TABLE,
    C._SQLITE_CREATE_TEMP_TRIGGER,
    C._SQLITE_CREATE_TEMP_VIEW,
    C._SQLITE_CREATE_TRIGGER,
    C._SQLITE_CREATE_VIEW,
    C._SQLITE_CREATE_VTABLE,
    C._SQLITE_DBCONFIG_DEFENSIVE,
    C._SQLITE_DBCONFIG_DQS_DDL,
    C._SQLITE_DBCONFIG_DQS_DML,
    C._SQLITE_DBCONFIG_ENABLE_FKEY,
    C._SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER,
    C._SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION,
    C._SQLITE_DBCONFIG_ENABLE_QPSG,
    C._SQLITE_DBCONFIG_ENABLE_TRIGGER,
    C._SQLITE_DBCONFIG_ENABLE_VIEW,
    C._SQLITE_DBCONFIG_LEGACY_ALTER_TABLE,
    C._SQLITE_DBCONFIG_LEGACY_FILE_FORMAT,
    C._SQLITE_DBCONFIG_LOOKASIDE,
    C._SQLITE_DBCONFIG_MAINDBNAME,
    C._SQLITE_DBCONFIG_MAX,
    C._SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE,
    C._SQLITE_DBCONFIG_RESET_DATABASE,
    C._SQLITE_DBCONFIG_TRIGGER_EQP,
    C._SQLITE_DBCONFIG_TRUSTED_SCHEMA,
    C._SQLITE_DBCONFIG_WRITABLE_SCHEMA,
    C._SQLITE_DBSTATUS_CACHE_HIT,
    C._SQLITE_DBSTATUS_CACHE_MISS,
    C._SQLITE_DBSTATUS_CACHE_SPILL,
    C._SQLITE_DBSTATUS_CACHE_USED,
    C._SQLITE_DBSTATUS_CACHE_USED_SHARED,
    C._SQLITE_DBSTATUS_CACHE_WRITE,
    C._SQLITE_DBSTATUS_DEFERRED_FKS,
    C._SQLITE_DBSTATUS_LOOKASIDE_HIT,
    C._SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL,
    C._SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE,
    C._SQLITE_DBSTATUS_LOOKASIDE_USED,
    C._SQLITE_DBSTATUS_MAX,
    C._SQLITE_DBSTATUS_SCHEMA_USED,
    C._SQLITE_DBSTATUS_STMT_USED,
    C._SQLITE_DELETE,
    C._SQLITE_DENY,
    C._SQLITE_DESERIALIZE_FREEONCLOSE,
    C._SQLITE_DESERIALIZE_READONLY,
    C._SQLITE_DESERIALIZE_RESIZEABLE,
    C._SQLITE_DETACH,
    C._SQLITE_DETERMINISTIC,
    C._SQLITE_DIRECTONLY,
    C._SQLITE_DONE,
    C._SQLITE_DROP_INDEX,
    C._SQLITE_DROP_TABLE,
    C._SQLITE_DROP_TEMP_INDEX,
    C._SQLITE_DROP_TEMP_TABLE,
    C._SQLITE_DROP_TEMP_TRIGGER,
    C._SQLITE_DROP_TEMP_VIEW,
    C._SQLITE_DROP_TRIGGER,
    C._SQLITE_DROP_VIEW,
    C._SQLITE_DROP_VTABLE,
    C._SQLITE_EMPTY,
    C._SQLITE_ERROR,
    C._SQLITE_ERROR_MISSING_COLLSEQ,
    C._SQLITE_ERROR_RETRY,
    C._SQLITE_ERROR_SNAPSHOT,
    C._SQLITE_FAIL,
    C._SQLITE_FCNTL_BEGIN_ATOMIC_WRITE,
    C._SQLITE_FCNTL_BUSYHANDLER,
    C._SQLITE_FCNTL_CHUNK_SIZE,
    C._SQLITE_FCNTL_CKPT_DONE,
    C._SQLITE_FCNTL_CKPT_START,
    C._SQLITE_FCNTL_CKSM_FILE,
    C._SQLITE_FCNTL_COMMIT_ATOMIC_WRITE,
    C._SQLITE_FCNTL_COMMIT_PHASETWO,
    C._SQLITE_FCNTL_DATA_VERSION,
    C._SQLITE_FCNTL_EXTERNAL_READER,
    C._SQLITE_FCNTL_FILE_POINTER,
    C._SQLITE_FCNTL_GET_LOCKPROXYFILE,
    C._SQLITE_FCNTL_HAS_MOVED,
    C._SQLITE_FCNTL_JOURNAL_POINTER,
    C._SQLITE_FCNTL_LAST_ERRNO,
    C._SQLITE_FCNTL_LOCKSTATE,
    C._SQLITE_FCNTL_LOCK_TIMEOUT,
    C._SQLITE_FCNTL_MMAP_SIZE,
    C._SQLITE_FCNTL_OVERWRITE,
    C._SQLITE_FCNTL_PDB,
    C._SQLITE_FCNTL_PERSIST_WAL,
    C._SQLITE_FCNTL_POWERSAFE_OVERWRITE,
    C._SQLITE_FCNTL_PRAGMA,
    C._SQLITE_FCNTL_RBU,
    C._SQLITE_FCNTL_RESERVE_BYTES,
    C._SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE,
    C._SQLITE_FCNTL_SET_LOCKPROXYFILE,
    C._SQLITE_FCNTL_SIZE_HINT,
    C._SQLITE_FCNTL_SIZE_LIMIT,
    C._SQLITE_FCNTL_SYNC,
    C._SQLITE_FCNTL_SYNC_OMITTED,
    C._SQLITE_FCNTL_TEMPFILENAME,
    C._SQLITE_FCNTL_TRACE,
    C._SQLITE_FCNTL_VFSNAME,
    C._SQLITE_FCNTL_VFS_POINTER,
    C._SQLITE_FCNTL_WAL_BLOCK,
    C._SQLITE_FCNTL_WIN32_AV_RETRY,
    C._SQLITE_FCNTL_WIN32_GET_HANDLE,
    C._SQLITE_FCNTL_WIN32_SET_HANDLE,
    C._SQLITE_FCNTL_ZIPVFS,
    C._SQLITE_FLOAT,
    C._SQLITE_FORMAT,
    C._SQLITE_FULL,
    C._SQLITE_FUNCTION,
    C._SQLITE_IGNORE,
    C._SQLITE_INDEX_CONSTRAINT_EQ,
    C._SQLITE_INDEX_CONSTRAINT_FUNCTION,
    C._SQLITE_INDEX_CONSTRAINT_GE,
    C._SQLITE_INDEX_CONSTRAINT_GLOB,
    C._SQLITE_INDEX_CONSTRAINT_GT,
    C._SQLITE_INDEX_CONSTRAINT_IS,
    C._SQLITE_INDEX_CONSTRAINT_ISNOT,
    C._SQLITE_INDEX_CONSTRAINT_ISNOTNULL,
    C._SQLITE_INDEX_CONSTRAINT_ISNULL,
    C._SQLITE_INDEX_CONSTRAINT_LE,
    C._SQLITE_INDEX_CONSTRAINT_LIKE,
    C._SQLITE_INDEX_CONSTRAINT_LIMIT,
    C._SQLITE_INDEX_CONSTRAINT_LT,
    C._SQLITE_INDEX_CONSTRAINT_MATCH,
    C._SQLITE_INDEX_CONSTRAINT_NE,
    C._SQLITE_INDEX_CONSTRAINT_OFFSET,
    C._SQLITE_INDEX_CONSTRAINT_REGEXP,
    C._SQLITE_INDEX_SCAN_UNIQUE,
    C._SQLITE_INNOCUOUS,
    C._SQLITE_INSERT,
    C._SQLITE_INTEGER,
    C._SQLITE_INTERNAL,
    C._SQLITE_INTERRUPT,
    C._SQLITE_IOCAP_ATOMIC,
    C._SQLITE_IOCAP_ATOMIC16K,
    C._SQLITE_IOCAP_ATOMIC1K,
    C._SQLITE_IOCAP_ATOMIC2K,
    C._SQLITE_IOCAP_ATOMIC32K,
    C._SQLITE_IOCAP_ATOMIC4K,
    C._SQLITE_IOCAP_ATOMIC512,
    C._SQLITE_IOCAP_ATOMIC64K,
    C._SQLITE_IOCAP_ATOMIC8K,
    C._SQLITE_IOCAP_BATCH_ATOMIC,
    C._SQLITE_IOCAP_IMMUTABLE,
    C._SQLITE_IOCAP_POWERSAFE_OVERWRITE,
    C._SQLITE_IOCAP_SAFE_APPEND,
    C._SQLITE_IOCAP_SEQUENTIAL,
    C._SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN,
    C._SQLITE_IOERR,
    C._SQLITE_IOERR_ACCESS,
    C._SQLITE_IOERR_AUTH,
    C._SQLITE_IOERR_BEGIN_ATOMIC,
    C._SQLITE_IOERR_BLOCKED,
    C._SQLITE_IOERR_CHECKRESERVEDLOCK,
    C._SQLITE_IOERR_CLOSE,
    C._SQLITE_IOERR_COMMIT_ATOMIC,
    C._SQLITE_IOERR_CONVPATH,
    C._SQLITE_IOERR_CORRUPTFS,
    C._SQLITE_IOERR_DATA,
    C._SQLITE_IOERR_DELETE,
    C._SQLITE_IOERR_DELETE_NOENT,
    C._SQLITE_IOERR_DIR_CLOSE,
    C._SQLITE_IOERR_DIR_FSYNC,
    C._SQLITE_IOERR_FSTAT,
    C._SQLITE_IOERR_FSYNC,
    C._SQLITE_IOERR_GETTEMPPATH,
    C._SQLITE_IOERR_LOCK,
    C._SQLITE_IOERR_MMAP,
    C._SQLITE_IOERR_NOMEM,
    C._SQLITE_IOERR_RDLOCK,
    C._SQLITE_IOERR_READ,
    C._SQLITE_IOERR_ROLLBACK_ATOMIC,
    C._SQLITE_IOERR_SEEK,
    C._SQLITE_IOERR_SHMLOCK,
    C._SQLITE_IOERR_SHMMAP,
    C._SQLITE_IOERR_SHMOPEN,
    C._SQLITE_IOERR_SHMSIZE,
    C._SQLITE_IOERR_SHORT_READ,
    C._SQLITE_IOERR_TRUNCATE,
    C._SQLITE_IOERR_UNLOCK,
    C._SQLITE_IOERR_VNODE,
    C._SQLITE_IOERR_WRITE,
    C._SQLITE_LIMIT_ATTACHED,
    C._SQLITE_LIMIT_COLUMN,
    C._SQLITE_LIMIT_COMPOUND_SELECT,
    C._SQLITE_LIMIT_EXPR_DEPTH,
    C._SQLITE_LIMIT_FUNCTION_ARG,
    C._SQLITE_LIMIT_LENGTH,
    C._SQLITE_LIMIT_LIKE_PATTERN_LENGTH,
    C._SQLITE_LIMIT_SQL_LENGTH,
    C._SQLITE_LIMIT_TRIGGER_DEPTH,
    C._SQLITE_LIMIT_VARIABLE_NUMBER,
    C._SQLITE_LIMIT_VDBE_OP,
    C._SQLITE_LIMIT_WORKER_THREADS,
    C._SQLITE_LOCKED,
    C._SQLITE_LOCKED_SHAREDCACHE,
    C._SQLITE_LOCKED_VTAB,
    C._SQLITE_LOCK_EXCLUSIVE,
    C._SQLITE_LOCK_NONE,
    C._SQLITE_LOCK_PENDING,
    C._SQLITE_LOCK_RESERVED,
    C._SQLITE_LOCK_SHARED,
    C._SQLITE_MISMATCH,
    C._SQLITE_MISUSE,
    C._SQLITE_MUTEX_FAST,
    C._SQLITE_MUTEX_RECURSIVE,
    C._SQLITE_MUTEX_STATIC_APP1,
    C._SQLITE_MUTEX_STATIC_APP2,
    C._SQLITE_MUTEX_STATIC_APP3,
    C._SQLITE_MUTEX_STATIC_LRU,
    C._SQLITE_MUTEX_STATIC_LRU2,
    C._SQLITE_MUTEX_STATIC_MAIN,
    C._SQLITE_MUTEX_STATIC_MEM,
    C._SQLITE_MUTEX_STATIC_MEM2,
    C._SQLITE_MUTEX_STATIC_OPEN,
    C._SQLITE_MUTEX_STATIC_PMEM,
    C._SQLITE_MUTEX_STATIC_PRNG,
    C._SQLITE_MUTEX_STATIC_VFS1,
    C._SQLITE_MUTEX_STATIC_VFS2,
    C._SQLITE_MUTEX_STATIC_VFS3,
    C._SQLITE_NOLFS,
    C._SQLITE_NOMEM,
    C._SQLITE_NOTADB,
    C._SQLITE_NOTFOUND,
    C._SQLITE_NOTICE,
    C._SQLITE_NOTICE_RECOVER_ROLLBACK,
    C._SQLITE_NOTICE_RECOVER_WAL,
    C._SQLITE_NULL,
    C._SQLITE_OK,
    C._SQLITE_OK_LOAD_PERMANENTLY,
    C._SQLITE_OK_SYMLINK,
    C._SQLITE_OPEN_AUTOPROXY,
    C._SQLITE_OPEN_DELETEONCLOSE,
    C._SQLITE_OPEN_EXCLUSIVE,
    C._SQLITE_OPEN_MAIN_DB,
    C._SQLITE_OPEN_MAIN_JOURNAL,
    C._SQLITE_OPEN_SUBJOURNAL,
    C._SQLITE_OPEN_SUPER_JOURNAL,
    C._SQLITE_OPEN_TEMP_DB,
    C._SQLITE_OPEN_TEMP_JOURNAL,
    C._SQLITE_OPEN_TRANSIENT_DB,
    C._SQLITE_OPEN_WAL,
    C._SQLITE_PERM,
    C._SQLITE_PRAGMA,
    C._SQLITE_PREPARE_NORMALIZE,
    C._SQLITE_PREPARE_NO_VTAB,
    C._SQLITE_PREPARE_PERSISTENT,
    C._SQLITE_PROTOCOL,
    C._SQLITE_RANGE,
    C._SQLITE_READ,
    C._SQLITE_READONLY,
    C._SQLITE_READONLY_CANTINIT,
    C._SQLITE_READONLY_CANTLOCK,
    C._SQLITE_READONLY_DBMOVED,
    C._SQLITE_READONLY_DIRECTORY,
    C._SQLITE_READONLY_RECOVERY,
    C._SQLITE_READONLY_ROLLBACK,
    C._SQLITE_RECURSIVE,
    C._SQLITE_REINDEX,
    C._SQLITE_REPLACE,
    C._SQLITE_ROLLBACK,
    C._SQLITE_ROW,
    C._SQLITE_SAVEPOINT,
    C._SQLITE_SCANSTAT_EST,
    C._SQLITE_SCANSTAT_EXPLAIN,
    C._SQLITE_SCANSTAT_NAME,
    C._SQLITE_SCANSTAT_NLOOP,
    C._SQLITE_SCANSTAT_NVISIT,
    C._SQLITE_SCANSTAT_SELECTID,
    C._SQLITE_SCHEMA,
    C._SQLITE_SELECT,
    C._SQLITE_SERIALIZE_NOCOPY,
    C._SQLITE_SHM_EXCLUSIVE,
    C._SQLITE_SHM_LOCK,
    C._SQLITE_SHM_NLOCK,
    C._SQLITE_SHM_SHARED,
    C._SQLITE_SHM_UNLOCK,
    C._SQLITE_SOURCE_ID,
    C._SQLITE_STATIC,
    C._SQLITE_STATUS_MALLOC_COUNT,
    C._SQLITE_STATUS_MALLOC_SIZE,
    C._SQLITE_STATUS_MEMORY_USED,
    C._SQLITE_STATUS_PAGECACHE_OVERFLOW,
    C._SQLITE_STATUS_PAGECACHE_SIZE,
    C._SQLITE_STATUS_PAGECACHE_USED,
    C._SQLITE_STATUS_PARSER_STACK,
    C._SQLITE_STATUS_SCRATCH_OVERFLOW,
    C._SQLITE_STATUS_SCRATCH_SIZE,
    C._SQLITE_STATUS_SCRATCH_USED,
    C._SQLITE_STMTSTATUS_AUTOINDEX,
    C._SQLITE_STMTSTATUS_FILTER_HIT,
    C._SQLITE_STMTSTATUS_FILTER_MISS,
    C._SQLITE_STMTSTATUS_FULLSCAN_STEP,
    C._SQLITE_STMTSTATUS_MEMUSED,
    C._SQLITE_STMTSTATUS_REPREPARE,
    C._SQLITE_STMTSTATUS_RUN,
    C._SQLITE_STMTSTATUS_SORT,
    C._SQLITE_STMTSTATUS_VM_STEP,
    C._SQLITE_SUBTYPE,
    C._SQLITE_SYNC_DATAONLY,
    C._SQLITE_SYNC_FULL,
    C._SQLITE_SYNC_NORMAL,
    C._SQLITE_TESTCTRL_ALWAYS,
    C._SQLITE_TESTCTRL_ASSERT,
    C._SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS,
    C._SQLITE_TESTCTRL_BITVEC_TEST,
    C._SQLITE_TESTCTRL_BYTEORDER,
    C._SQLITE_TESTCTRL_EXPLAIN_STMT,
    C._SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS,
    C._SQLITE_TESTCTRL_FAULT_INSTALL,
    C._SQLITE_TESTCTRL_FIRST,
    C._SQLITE_TESTCTRL_IMPOSTER,
    C._SQLITE_TESTCTRL_INTERNAL_FUNCTIONS,
    C._SQLITE_TESTCTRL_ISINIT,
    C._SQLITE_TESTCTRL_ISKEYWORD,
    C._SQLITE_TESTCTRL_LAST,
    C._SQLITE_TESTCTRL_LOCALTIME_FAULT,
    C._SQLITE_TESTCTRL_LOGEST,
    C._SQLITE_TESTCTRL_NEVER_CORRUPT,
    C._SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD,
    C._SQLITE_TESTCTRL_OPTIMIZATIONS,
    C._SQLITE_TESTCTRL_PARSER_COVERAGE,
    C._SQLITE_TESTCTRL_PENDING_BYTE,
    C._SQLITE_TESTCTRL_PRNG_RESET,
    C._SQLITE_TESTCTRL_PRNG_RESTORE,
    C._SQLITE_TESTCTRL_PRNG_SAVE,
    C._SQLITE_TESTCTRL_PRNG_SEED,
    C._SQLITE_TESTCTRL_RESERVE,
    C._SQLITE_TESTCTRL_RESULT_INTREAL,
    C._SQLITE_TESTCTRL_SCRATCHMALLOC,
    C._SQLITE_TESTCTRL_SEEK_COUNT,
    C._SQLITE_TESTCTRL_SORTER_MMAP,
    C._SQLITE_TESTCTRL_TRACEFLAGS,
    C._SQLITE_TESTCTRL_TUNE,
    C._SQLITE_TESTCTRL_VDBE_COVERAGE,
    C._SQLITE_TEXT,
    C._SQLITE_TOOBIG,
    C._SQLITE_TRACE_CLOSE,
    C._SQLITE_TRACE_PROFILE,
    C._SQLITE_TRACE_ROW,
    C._SQLITE_TRACE_STMT,
    C._SQLITE_TRANSACTION,
    C._SQLITE_TRANSIENT,
    C._SQLITE_TXN_NONE,
    C._SQLITE_TXN_READ,
    C._SQLITE_TXN_WRITE,
    C._SQLITE_UPDATE,
    C._SQLITE_UTF16,
    C._SQLITE_UTF16BE,
    C._SQLITE_UTF16LE,
    C._SQLITE_UTF16_ALIGNED,
    C._SQLITE_UTF8,
    C._SQLITE_VERSION,
    C._SQLITE_VERSION_NUMBER,
    C._SQLITE_VTAB_CONSTRAINT_SUPPORT,
    C._SQLITE_VTAB_DIRECTONLY,
    C._SQLITE_VTAB_INNOCUOUS,
    C._SQLITE_WARNING,
    C._SQLITE_WARNING_AUTOINDEX,
    C._SQLITE_WIN32_DATA_DIRECTORY_TYPE,
    C._SQLITE_WIN32_TEMP_DIRECTORY_TYPE,
  )
where

import Data.Bits ((.|.))
import Data.Coerce (coerce)
import Foreign.C (CInt (..))
import qualified Sqlite3.Bindings.C as C

-- | https://www.sqlite.org/c3ref/c_blob.html
newtype SQLITE_DATATYPE
  = SQLITE_DATATYPE CInt
  deriving stock (Eq)

instance Show SQLITE_DATATYPE where
  show = \case
    SQLITE_INTEGER -> "SQLITE_INTEGER"
    SQLITE_FLOAT -> "SQLITE_FLOAT"
    SQLITE_TEXT -> "SQLITE_TEXT"
    SQLITE_BLOB -> "SQLITE_BLOB"
    SQLITE_NULL -> "SQLITE_NULL"

pattern SQLITE_INTEGER :: SQLITE_DATATYPE
pattern SQLITE_INTEGER <-
  ((== SQLITE_DATATYPE C._SQLITE_INTEGER) -> True)
  where
    SQLITE_INTEGER = SQLITE_DATATYPE C._SQLITE_INTEGER

pattern SQLITE_FLOAT :: SQLITE_DATATYPE
pattern SQLITE_FLOAT <-
  ((== SQLITE_DATATYPE C._SQLITE_FLOAT) -> True)
  where
    SQLITE_FLOAT = SQLITE_DATATYPE C._SQLITE_FLOAT

pattern SQLITE_TEXT :: SQLITE_DATATYPE
pattern SQLITE_TEXT <-
  ((== SQLITE_DATATYPE C._SQLITE_TEXT) -> True)
  where
    SQLITE_TEXT = SQLITE_DATATYPE C._SQLITE_TEXT

pattern SQLITE_BLOB :: SQLITE_DATATYPE
pattern SQLITE_BLOB <-
  ((== SQLITE_DATATYPE C._SQLITE_BLOB) -> True)
  where
    SQLITE_BLOB = SQLITE_DATATYPE C._SQLITE_BLOB

pattern SQLITE_NULL :: SQLITE_DATATYPE
pattern SQLITE_NULL <-
  ((== SQLITE_DATATYPE C._SQLITE_NULL) -> True)
  where
    SQLITE_NULL = SQLITE_DATATYPE C._SQLITE_NULL

{-# COMPLETE
  SQLITE_INTEGER,
  SQLITE_FLOAT,
  SQLITE_TEXT,
  SQLITE_BLOB,
  SQLITE_NULL
  #-}

-- | https://www.sqlite.org/c3ref/c_open_autoproxy.html
newtype SQLITE_OPEN_FLAGS
  = SQLITE_OPEN_FLAGS CInt
  deriving stock (Eq)

instance Monoid SQLITE_OPEN_FLAGS where
  mappend = (<>)
  mempty = SQLITE_OPEN_FLAGS 0

instance Semigroup SQLITE_OPEN_FLAGS where
  (<>) =
    coerce ((.|.) :: CInt -> CInt -> CInt)

pattern SQLITE_OPEN_EXRESCODE :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_EXRESCODE <-
  ((== SQLITE_OPEN_FLAGS C._SQLITE_OPEN_EXRESCODE) -> True)
  where
    SQLITE_OPEN_EXRESCODE = SQLITE_OPEN_FLAGS C._SQLITE_OPEN_EXRESCODE

pattern SQLITE_OPEN_FULLMUTEX :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_FULLMUTEX <-
  ((== SQLITE_OPEN_FLAGS C._SQLITE_OPEN_FULLMUTEX) -> True)
  where
    SQLITE_OPEN_FULLMUTEX = SQLITE_OPEN_FLAGS C._SQLITE_OPEN_FULLMUTEX

pattern SQLITE_OPEN_MEMORY :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_MEMORY <-
  ((== SQLITE_OPEN_FLAGS C._SQLITE_OPEN_MEMORY) -> True)
  where
    SQLITE_OPEN_MEMORY = SQLITE_OPEN_FLAGS C._SQLITE_OPEN_MEMORY

pattern SQLITE_OPEN_NOFOLLOW :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_NOFOLLOW <-
  ((== SQLITE_OPEN_FLAGS C._SQLITE_OPEN_NOFOLLOW) -> True)
  where
    SQLITE_OPEN_NOFOLLOW = SQLITE_OPEN_FLAGS C._SQLITE_OPEN_NOFOLLOW

pattern SQLITE_OPEN_NOMUTEX :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_NOMUTEX <-
  ((== SQLITE_OPEN_FLAGS C._SQLITE_OPEN_NOMUTEX) -> True)
  where
    SQLITE_OPEN_NOMUTEX = SQLITE_OPEN_FLAGS C._SQLITE_OPEN_NOMUTEX

pattern SQLITE_OPEN_URI :: SQLITE_OPEN_FLAGS
pattern SQLITE_OPEN_URI <-
  ((== SQLITE_OPEN_FLAGS C._SQLITE_OPEN_URI) -> True)
  where
    SQLITE_OPEN_URI = SQLITE_OPEN_FLAGS C._SQLITE_OPEN_URI

{-# COMPLETE
  SQLITE_OPEN_EXRESCODE,
  SQLITE_OPEN_FULLMUTEX,
  SQLITE_OPEN_MEMORY,
  SQLITE_OPEN_NOFOLLOW,
  SQLITE_OPEN_NOMUTEX,
  SQLITE_OPEN_URI
  #-}

-- | https://www.sqlite.org/c3ref/c_open_autoproxy.html
newtype SQLITE_OPEN_MODE
  = SQLITE_OPEN_MODE CInt
  deriving stock (Eq)

instance Show SQLITE_OPEN_MODE where
  show = \case
    SQLITE_OPEN_READONLY -> "SQLITE_OPEN_READONLY"
    SQLITE_OPEN_READWRITE -> "SQLITE_OPEN_READWRITE"
    SQLITE_OPEN_CREATE -> "SQLITE_OPEN_CREATE"

pattern SQLITE_OPEN_READONLY :: SQLITE_OPEN_MODE
pattern SQLITE_OPEN_READONLY <-
  ((== SQLITE_OPEN_MODE C._SQLITE_OPEN_READONLY) -> True)
  where
    SQLITE_OPEN_READONLY = SQLITE_OPEN_MODE C._SQLITE_OPEN_READONLY

pattern SQLITE_OPEN_READWRITE :: SQLITE_OPEN_MODE
pattern SQLITE_OPEN_READWRITE <-
  ((== SQLITE_OPEN_MODE C._SQLITE_OPEN_READWRITE) -> True)
  where
    SQLITE_OPEN_READWRITE = SQLITE_OPEN_MODE C._SQLITE_OPEN_READWRITE

pattern SQLITE_OPEN_CREATE :: SQLITE_OPEN_MODE
pattern SQLITE_OPEN_CREATE <-
  ((== SQLITE_OPEN_MODE (C._SQLITE_OPEN_READWRITE .|. C._SQLITE_OPEN_CREATE)) -> True)
  where
    SQLITE_OPEN_CREATE =
      SQLITE_OPEN_MODE (C._SQLITE_OPEN_READWRITE .|. C._SQLITE_OPEN_CREATE)

{-# COMPLETE SQLITE_OPEN_READONLY, SQLITE_OPEN_READWRITE, SQLITE_OPEN_CREATE #-}
